In [3]:
# 0D tensors
import numpy as np
a = np.array(5)
print(a)
print(a.ndim)

5
0


In [4]:
a = np.array([1,2,3,4])
print(a)
print(a.ndim)

[1 2 3 4]
1


In [6]:
mat = np.array([[1,2,3],
               [4,5,6]])
print(mat)
print(mat.ndim)

[[1 2 3]
 [4 5 6]]
2


In [7]:
mat = np.array([[[1,2,3],[1,2,3]], [[1,2,3],[1,2,3]]])
print(mat)
print(mat.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3


In [12]:
mat = np.array([[[[1,2,3],[1,2,3]], [[1,2,3],[1,2,3]]], [[[1,2,3],[1,2,3]], [[1,2,3],[1,2,3]]]])
print(mat)
print(mat.ndim)
# print(mat.rank)
print(mat.shape)

# The total number of elements is:
# \(2 \times 2 \times 3 \times 4 = 48\)
# 3. Compare different shapes
# Shape	Interpretation
# (3,)	1D array with 3 elements
# (2, 3)	2D matrix with 2 rows and 3 columns
# (4, 2, 3)	4 matrices, each with 2 rows and 3 columns
# (2, 4, 2, 3)	2 groups, each with 4 matrices of shape 2 × 3
# (2, 2, 3, 4)	2 groups, each with 2 matrices of shape 3 × 4
# The key point: A shape tuple tells you how many elements exist along each axis, not the values stored in the tensor.
# In your original example, (2, 2, 2, 3) means two 3D tensors, each containing two matrices, with two rows and three columns per matrix.

# 1. Let's take (2, 2, 3, 4) as an example
# Imagine you have a 4D tensor with this shape:
# mat.shape = (2, 2, 3, 4)



# Read it from left to right:
# - First 2: 2 groups of 3D tensors.
# - Second 2: Each group contains 2 matrices.
# - Third 3: Each matrix has 3 rows.
# - Fourth 4: Each row has 4 elements (columns).
# Visualization of (2, 2, 3, 4)
# Group 1 (3D tensor)
# Matrix 1
# 1

# 2

# 3

# 4


# 5

# 6

# 7

# 8


# 9

# 10

# 11

# 12




# Matrix 2
# 1

# 2

# 3

# 4


# 5

# 6

# 7

# 8


# 9

# 10

# 11

# 12






# Group 2 (3D tensor)
# Matrix 1
# 1

# 2

# 3

# 4


# 5

# 6

# 7

# 8


# 9

# 10

# 11

# 12




# Matrix 2
# 1

# 2

# 3

# 4


# 5

# 6

# 7

# 8


# 9

# 10

# 11

# 12






# Illustrative values to show the structure. Each group has two 3 × 4 matrices.

[[[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]]
4
(2, 2, 2, 3)


In [16]:
# import numpy as np

# # 0D
# arr0 = np.zeros(())

# # 1D
# arr1 = np.zeros((3,))

# # 2D
# arr2 = np.zeros((2, 3))

# # 3D
# arr3 = np.zeros((2, 2, 3))

# # 4D
# arr4 = np.zeros((2, 2, 2, 3))

# # 5D
# arr5 = np.zeros((2, 2, 2, 2, 3))


# for arr in [arr0, arr1, arr2, arr3, arr4, arr5]:
#     print("Shape:", arr.shape)
#     print("Dimensions:", arr.ndim)
#     print("Total elements:", arr.size)
#     print("-------------------")

mat_zeros = np.zeros((2,2,2,3))
mat_ones = np.ones((2,2,2,3))

print(mat_zeros.ndim)
print(mat_zeros.shape)
print(mat_zeros)

print(mat_ones.ndim)
print(mat_ones.shape)
print(mat_ones)

mat_array = np.array((2,2,2,3)) # it's just array gives, 1D
print(mat_array)

4
(2, 2, 2, 3)
[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]]
4
(2, 2, 2, 3)
[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]
[2 2 2 3]


In [17]:
mat_zeros_5d = np.zeros((2,2,2,3,3))
print(mat_zeros_5d.ndim)
print(mat_zeros_5d.shape)
print(mat_zeros_5d)

5
(2, 2, 2, 3, 3)
[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]]


In [18]:
## 1D - storing students placements data
### CG{A
student_3 = np.array([0.1, 9.0, 1, 1]) ### CGPA, 
print(student_3.ndim)
print(student_3.shape)

1
(4,)


In [21]:
### 2D - multiple students data
students = np.array([[0.1, 9.0, 4, 4],
                    [0.1, 9.0, 3, 3],
                    [0.1, 9.0, 2, 2],
])
print(students.ndim)
print(students.shape)

2
(3, 4)


In [22]:
### 3D - NLD data processing
### Time Series Data
students = np.array([[[0.1, 9.0, 4, 4],
                     [0.1, 9.0, 4, 4]]])
print(students)
print(students.ndim)
print(students.shape)

[[[0.1 9.  4.  4. ]
  [0.1 9.  4.  4. ]]]
3
(1, 2, 4)


## 4D Tensor - Computer Vision
### Training a CNN on images

### shape = (batch, height, width, channels)
image_batch = np.random.rand(200, 200, 200, 3)
print(image_batch)
print(image_batch.ndim)
print(image_batch.shape)

In [25]:
### 5D Tensor - Video Processing  - 5D(batch, frames, height, width, channels)
video_batch = np.random.rand(5, 3, 2, 2, 1)
print(video_batch)
print(video_batch.ndim)
print(video_batch.shape)

[[[[[0.17573283]
    [0.98142866]]

   [[0.61487039]
    [0.32906871]]]


  [[[0.11122426]
    [0.67396414]]

   [[0.32307029]
    [0.05223642]]]


  [[[0.40560027]
    [0.70685117]]

   [[0.55440516]
    [0.77474844]]]]



 [[[[0.51387452]
    [0.13585774]]

   [[0.37122135]
    [0.41800909]]]


  [[[0.7184159 ]
    [0.96218468]]

   [[0.95808362]
    [0.17249122]]]


  [[[0.84025372]
    [0.49040965]]

   [[0.03522379]
    [0.71652182]]]]



 [[[[0.19661092]
    [0.12645764]]

   [[0.22330023]
    [0.39181287]]]


  [[[0.03781857]
    [0.18142535]]

   [[0.37764572]
    [0.34334664]]]


  [[[0.84347043]
    [0.41700161]]

   [[0.8701645 ]
    [0.62534254]]]]



 [[[[0.79470979]
    [0.21337782]]

   [[0.77896857]
    [0.37311909]]]


  [[[0.60327249]
    [0.67047533]]

   [[0.6133493 ]
    [0.63750338]]]


  [[[0.15167777]
    [0.62616712]]

   [[0.9199799 ]
    [0.90153149]]]]



 [[[[0.99769213]
    [0.33169411]]

   [[0.23783788]
    [0.89376079]]]


  [[[0.34219884]
    [0.679071